[project]
name = "quickshell"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "evdev>=1.9.2",
    "psutil>=7.1.3",
]

[dependency-groups]
dev = [
    "mypy>=1.18.2",
]

[tool.mypy]
follow_untyped_imports = true
